// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const createCandles = `-- name: CreateCandles :batchexec
INSERT INTO candles
    (
        symbol     ,
        open_price ,
        close_price,
        low_price  ,
        high_price ,
        interval   ,
        volume     ,
        open_time  ,
        close_time ,
        is_closed
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10
    )
    ON CONFLICT
    (
        symbol  ,
        interval,
        open_time
    )
    DO NOTHING
`

type CreateCandlesBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type CreateCandlesParams struct {
	Symbol     string
	OpenPrice  pgtype.Numeric
	ClosePrice pgtype.Numeric
	LowPrice   pgtype.Numeric
	HighPrice  pgtype.Numeric
	Interval   string
	Volume     pgtype.Numeric
	OpenTime   pgtype.Timestamp
	CloseTime  pgtype.Timestamp
	IsClosed   bool
}

func (q *Queries) CreateCandles(ctx context.Context, arg []CreateCandlesParams) *CreateCandlesBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Symbol,
			a.OpenPrice,
			a.ClosePrice,
			a.LowPrice,
			a.HighPrice,
			a.Interval,
			a.Volume,
			a.OpenTime,
			a.CloseTime,
			a.IsClosed,
		}
		batch.Queue(createCandles, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &CreateCandlesBatchResults{br, len(arg), false}
}

func (b *CreateCandlesBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *CreateCandlesBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const createIndicators = `-- name: CreateIndicators :batchexec
INSERT INTO indicators (
    symbol,
    interval,
    indicator_name,
    period,
    candle_time,
    value
)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (symbol, interval, indicator_name, period, candle_time)
DO NOTHING
`

type CreateIndicatorsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type CreateIndicatorsParams struct {
	Symbol        string
	Interval      string
	IndicatorName string
	Period        pgtype.Int4
	CandleTime    pgtype.Timestamptz
	Value         pgtype.Numeric
}

func (q *Queries) CreateIndicators(ctx context.Context, arg []CreateIndicatorsParams) *CreateIndicatorsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Symbol,
			a.Interval,
			a.IndicatorName,
			a.Period,
			a.CandleTime,
			a.Value,
		}
		batch.Queue(createIndicators, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &CreateIndicatorsBatchResults{br, len(arg), false}
}

func (b *CreateIndicatorsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *CreateIndicatorsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
