// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Candle struct {
	ID         int32
	Symbol     string
	OpenPrice  pgtype.Numeric
	ClosePrice pgtype.Numeric
	LowPrice   pgtype.Numeric
	HighPrice  pgtype.Numeric
	Interval   string
	Volume     pgtype.Numeric
	CreatedAt  pgtype.Timestamp
	OpenTime   pgtype.Timestamp
	CloseTime  pgtype.Timestamp
	IsClosed   bool
}

type Indicator struct {
	ID            int64
	Symbol        string
	Interval      string
	IndicatorName string
	Period        pgtype.Int4
	CandleTime    pgtype.Timestamptz
	Value         pgtype.Numeric
	CreatedAt     pgtype.Timestamptz
}

type Symbol struct {
	ID         int64
	Exchange   string
	Symbol     string
	BaseAsset  pgtype.Text
	QuoteAsset pgtype.Text
	CreatedAt  pgtype.Timestamp
}
