// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Symbol struct {
	ID         int64
	Exchange   string
	Symbol     string
	BaseAsset  pgtype.Text
	QuoteAsset pgtype.Text
	CreatedAt  pgtype.Timestamp
}
