// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: symbols.sql

package db

import (
	"context"
)

const getSymbolByID = `-- name: GetSymbolByID :one
SELECT id, exchange, symbol, base_asset, quote_asset, created_at
FROM symbols
WHERE id = $1
`

func (q *Queries) GetSymbolByID(ctx context.Context, id int64) (Symbol, error) {
	row := q.db.QueryRow(ctx, getSymbolByID, id)
	var i Symbol
	err := row.Scan(
		&i.ID,
		&i.Exchange,
		&i.Symbol,
		&i.BaseAsset,
		&i.QuoteAsset,
		&i.CreatedAt,
	)
	return i, err
}

const getSymbols = `-- name: GetSymbols :many
SELECT id, exchange, symbol, base_asset, quote_asset, created_at
FROM symbols
`

func (q *Queries) GetSymbols(ctx context.Context) ([]Symbol, error) {
	rows, err := q.db.Query(ctx, getSymbols)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Symbol
	for rows.Next() {
		var i Symbol
		if err := rows.Scan(
			&i.ID,
			&i.Exchange,
			&i.Symbol,
			&i.BaseAsset,
			&i.QuoteAsset,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
